Temporal buffers and fifo tree
danielespo/Solving-SAT-in-FPGA-UCSB pull request #37
Opened 2024-07-22 23:20 UTC by zeilerphone

temporal buffers pass testbench

2024-07-22 23:31 UTC, danielespo approved these changes

2024-07-26 05:44 UTC, Chutian-Wang requested changes
Please see my comments. I think a minor change will improve our code portability.

2024-07-26 05:44 UTC, Chutian-Wang commented on rtl/src/Temporal_Buffer.v
> +    parameter NSAT_BITS = 2
`parameter REDUCE = 1`
and then replace `NSAT_BITS` with `NSAT - REDUCE`
REDUCE will be the number of variables that are known to be unsat and therefore need not be evaluated by the clause evaluator nor be stored in the temp buffer.
I had a similar config in my most recent PR in Clause_Evaluator.v and Clause_Evaluator_Cluster.v so you can check them out. The rational for this REDUCE factor is to allow exotic problem constructs and solver design in the future.

2024-07-26 05:44 UTC, Chutian-Wang commented on rtl/src/Temporal_Buffer_Wrapper.v
> +    parameter NSAT_BITS = 2
Same here, I think adding a `REDUCE` param makes a lot of sense.

2024-08-02 22:31 UTC, merged